language: node_js
node_js:
  - "4.1"
services:
  - mysql
env:
  -NODE_ENV=travis
  -DB=mysql
before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS travis_test_database;'; fi"